### ISSUE TITLE
Collect on Scrape

### ISSUE THREAD

**Issue by crutonjohn** [manofcolombia/bytesized-metrics#1]
Instead of running on a loop, the collection should run when metrics are requested.

**Comment by crutonjohn** [comment]
rycus86/prometheus_flask_exporter - This Flask exporter for Prometheus
    prometheus-flask-exporter README - Usage, examples, and configuration options
    prometheus-flask-exporter examples - Examples for setting up Flask app monitoring in different ways
    prometheus-flask-exporter on PyPI - This project on PyPI
    prometheus/client_python - The official Prometheus client library for Python

**Comment by crutonjohn** [comment]
https://stackoverflow.com/questions/807878/how-to-make-javascript-execute-after-page-load

**Comment by manofcolombia** [comment]
Resolved and merged in #12
